services:
    prueba_tecnica_double_v:
        container_name: ${APP_SERVICE}
        command: >
            sh -c "npm run serve"
        build: 
          context: .
          dockerfile: dockerfile
        image: node:20.0.0
        environment:
            HOST: "0.0.0.0"
            PORT: ${APP_PORT}
            CHOKIDAR_USEPOLLING: "true"
            WATCHPACK_POLLING: "true"
        ports:
            - '${APP_PORT}:${APP_PORT}'
        volumes:
            - '.:/var/www/html'
        working_dir: /var/www/html
        networks:
            - Double
networks:
    Double:
        name: Double
        driver: bridge